name: ecommerce_app
description: Flutter eCommerce app (official project for the Flutter Foundations course)

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.14.3
  flutter_layout_grid: 2.0.8
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: 4.0.1
  flutter_riverpod: ^2.6.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^15.1.1
  intl: ^0.19.0
  rxdart: ^0.28.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
  macos:
    generate: true
    image_path: "assets/app-icon.png"
  web:
    generate: true
    image_path: "assets/app-icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add all product images
    - assets/products/
