import '../features/products/domain/product.dart';

/// Test products to be used until a data source is implemented
const kTestProducts = [
  Product(
    id: '1',
    imageUrl: 'assets/menu/Cheeseburger.jpg',
    title: 'Cheeseburger',
    description: 'Classic grilled cheeseburger with lettuce and tomato.',
    price: 12.99,
    availableQuantity: 30,
    avgRating: 4.3,
    numRatings: 34,
  ),
  Product(
    id: '2',
    imageUrl: 'assets/menu/Margherita_Pizza.jpg',
    title: 'Margherita Pizza',
    description: 'Classic pizza with mozzarella and fresh basil.',
    price: 14.50,
    availableQuantity: 25,
    avgRating: 4.6,
    numRatings: 52,
  ),
  Product(
    id: '3',
    imageUrl: 'assets/menu/Pepperoni_Pizza.jpg',
    title: 'Pepperoni Pizza',
    description: 'Loaded pepperoni on a cheesy crust.',
    price: 15.00,
    availableQuantity: 40,
    avgRating: 4.7,
    numRatings: 45,
  ),
  Product(
    id: '4',
    imageUrl: 'assets/menu/Pasta_Carbonara.jpg',
    title: 'Pasta Carbonara',
    description: 'Creamy pasta with pancetta and parmesan.',
    price: 13.75,
    availableQuantity: 22,
    avgRating: 4.2,
    numRatings: 29,
  ),
  Product(
    id: '5',
    imageUrl: 'assets/menu/BBQ_Ribs.jpg',
    title: 'BBQ Ribs',
    description: 'Slow-cooked BBQ pork ribs with tangy sauce.',
    price: 18.99,
    availableQuantity: 15,
    avgRating: 4.8,
    numRatings: 60,
  ),
  Product(
    id: '6',
    imageUrl: 'assets/menu/Grilled_Chicken_Salad.jpeg',
    title: 'Grilled Chicken Salad',
    description: 'Fresh greens with grilled chicken and vinaigrette.',
    price: 11.00,
    availableQuantity: 35,
    avgRating: 4.1,
    numRatings: 18,
  ),
  Product(
    id: '7',
    imageUrl: 'assets/menu/Fish_and_Chips.jpg',
    title: 'Fish and Chips',
    description: 'Crispy battered fish with golden fries.',
    price: 14.20,
    availableQuantity: 20,
    avgRating: 4.5,
    numRatings: 26,
  ),
  Product(
    id: '8',
    imageUrl: 'assets/menu/Steak_Sandwich.jpg',
    title: 'Steak Sandwich',
    description: 'Sliced steak in a toasted bun with onions.',
    price: 16.00,
    availableQuantity: 18,
    avgRating: 4.4,
    numRatings: 33,
  ),
  Product(
    id: '9',
    imageUrl: 'assets/menu/Vegan_Wrap.jpg',
    title: 'Vegan Wrap',
    description: 'Healthy wrap with hummus and fresh veggies.',
    price: 9.99,
    availableQuantity: 50,
    avgRating: 4.0,
    numRatings: 10,
  ),
  Product(
    id: '10',
    imageUrl: 'assets/menu/Fettuccine_Alfredo.jpg',
    title: 'Fettuccine Alfredo',
    description: 'Rich creamy sauce over fettuccine noodles.',
    price: 13.25,
    availableQuantity: 28,
    avgRating: 4.6,
    numRatings: 21,
  ),
  Product(
    id: '11',
    imageUrl: 'assets/menu/Buffalo_Wings.jpg',
    title: 'Buffalo Wings',
    description: 'Spicy wings with a side of ranch.',
    price: 12.50,
    availableQuantity: 45,
    avgRating: 4.3,
    numRatings: 37,
  ),
  Product(
    id: '12',
    imageUrl: 'assets/menu/Chicken_Quesadilla.jpg',
    title: 'Chicken Quesadilla',
    description: 'Grilled tortilla filled with cheese and chicken.',
    price: 10.99,
    availableQuantity: 40,
    avgRating: 4.2,
    numRatings: 24,
  ),
  Product(
    id: '13',
    imageUrl: 'assets/menu/Shrimp_Tacos.jpg',
    title: 'Shrimp Tacos',
    description: 'Tacos filled with spicy shrimp and fresh toppings.',
    price: 13.99,
    availableQuantity: 17,
    avgRating: 4.7,
    numRatings: 19,
  ),
  Product(
    id: '14',
    imageUrl: 'assets/menu/Stuffed_Crust_Pizza.jpg',
    title: 'Stuffed Crust Pizza',
    description: 'Cheesy crust pizza with extra toppings.',
    price: 17.50,
    availableQuantity: 12,
    avgRating: 4.9,
    numRatings: 48,
  ),
  Product(
    id: '15',
    imageUrl: 'assets/menu/Mac_and_Cheese.jpg',
    title: 'Mac and Cheese',
    description: 'Creamy cheesy pasta baked to perfection.',
    price: 10.50,
    availableQuantity: 38,
    avgRating: 4.4,
    numRatings: 27,
  ),
];
